[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.22"
rust_version = "stable"

[features]
resolution = true
skip-lint = false

[programs.localnet]
arbitrage_bot = "138D5SkLsTLz8GmEMEYAntRPyvZXmiyR8Mb2rooDjx2A"
flash_loan = "HfsaDERzuB1m79Z1JHcbNz2JtwVcRowBso7xb5vWVQK"
mock_dex = "CP8F2b4Dh43ovvwJ6MBYXx9gKuFZ4zFvw9y74Ahk2wy6"
mock_pool = "BtJ6VkrNWjgfPVH63LevLiZYSoKGKfueS1d54i6jWfzq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://127.0.0.1:8899"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 0
validator = { url = "http://127.0.0.1:8899", ws_url = "ws://127.0.0.1:8900" }
